### ISSUE TITLE
Pre-live testing

### ISSUE THREAD

**Issue by Sumite321** [we-3hackathon/donum#47]
https://github.com/we-3hackathon/donum/blob/dea482232e9adebc48f6a5e6b372263f2b0ed7f5/ui-service/src/Components/Auth/Login.js#L129

- missing login/
- double "//"

**Comment by Sumite321** [comment]
**Addon**
https://github.com/we-3hackathon/donum/blob/dea482232e9adebc48f6a5e6b372263f2b0ed7f5/ui-service/src/Components/Auth/Register.js#L203

- missing register/

**Comment by Sumite321** [comment]
**Logic issues, authentication not working**

https://github.com/we-3hackathon/donum/blob/dea482232e9adebc48f6a5e6b372263f2b0ed7f5/ui-service/src/Components/Auth/Login.js#L138-L145

**Comment by Sharjeel50** [comment]
checking it out now

**Comment by Sumite321** [comment]
**Validation**

- Match for password & confirm password.

**General**

- Delete "React App" title to Donum.
- Box for "Agree terms and conditions" to be hidden, temporarily.

**Comment by Sumite321** [comment]
Pre-live complete
